dist: trusty
sudo: false
language: ruby
services:
  - postgresql
cache:
  bundler: true
env:
  global:
    - PAAS_USERNAME=gsd-deploy@digital.cabinet-office.gov.uk
    # PAAS_PASSWORD
    - secure: KOgddT+pu8ItC9IWMnxcB1b2tJRmIJ2/MOygQcYwXJiXjCPsUrZ6g6HdtXjqzrRoqtyIDkY41L6iZvHQ8p2epm+FRm1YAoZS265ZW0Cw1W2Dd5Jfy0nghebaZ6AODl35zBnViYt+1MJrHhfRBwW0iIQgMk3nuz8rRNZaUKkyM4lm54wsZs+8f/A1MQpCsKC/0Qt1TfTmpJVe3MIPRRWy+DRHDmItNEIFBSSeNOhcg2rioO8g9H7n/Rx193JvHlOODEViO1yOumXYkvfWHh77ycD7APNrDovdzqxL9HoP6XzyWxLLIY7K9rifPGNZXfN0xgX0wpWSecCshM+eelfvGNiHD8/S//HT23alYk437hyNa0VJHmfLvGD27P1IIR8/ASKx9x6lX7SOKIzMQUWAh7VGlEYIGNLy1T+MzoS4OPUl54PgUNpGuklVbWf9YrOW7SL/HAZRqMMFAsR13xsWkVfZgyPJaPIxeuW8E4lLJszjposWMoMdiGK/Yw516gkE2B3SBmHPGhp9abf1QcND6/nzRESplooN+dDpqbiZ3+JBiyes80uI+J7PdQyAQoYrvaDvEdt77binwggTNjxL7s2RUSM63IwtorARsLupbHs7ui9Jn4NjT3U+CQAXIv+xOK6EoiO5aHmBLEzz44Tf3Fo54bmfJCSrlFwfsMSsIQw=
before_script:
  - bundle config build.nokogiri --use-system-libraries
  - bundle install
  - npm install
  - cp config/database.yml.travis config/database.yml
  - bundle exec rails db:test:prepare
script:
  - bundle exec bundle-audit
  - bundle exec govuk-lint-ruby app lib spec
  - bundle exec brakeman
  - xvfb-run -a bundle exec rspec
  - npm run lint
  - ./script/run-npm-test
deploy:
  - provider: script
    script: ./etc/deploy.sh staging
    skip_cleanup: true
    on:
      branch: deploy
